server {
    listen 8080;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers "Range";
    add_header Access-Control-Expose-Headers "Content-Length,Content-Range";

    location / {
        root /srv/map;
        index index.html;
    }

    location /tiles/ {
        alias /srv/tiles/;
    }
}
